### PR TITLE
Add chemical viewer on hover

### PR DESCRIPTION
**Pull request by aislinblack**
Couldn't work in the drawing with the popper, so we have settled for a kind of viewing window above.

Testing: 
1. checkout branch
2. run the program
3. hover over a chemical and it should appear drawn above (if you hover over many chemicals quickly It might become slow)

### CODE REVIEW

**Comment by aislinblack** [comment]
[Have drawing pop up next to chemical in place of smile formula](https://trello.com/c/plZl99fi/10-have-drawing-pop-up-next-to-chemical-in-place-of-smile-formula)

**Comment by harbourcd** [comment]
Do we want the image to disappear if the user is not hovering over any chemical?

**Comment by aislinblack** [comment]
@harbourcd I was just going to allow it to stay, but we can ask Roman and Minte when we meet with them and that would be a pretty easy change to make

**Review by harbourcd — APPROVED** [review]

**Comment by aislinblack** [comment]
@harbourcd updated the window so the size is hard set so no shift bug

**Comment by klu17** [comment]
Hey. This viewer on hover works well with Chromium. On Firefox, the page hangs and molecules do not load.

**Pull request merged**
