### PR TITLE
Use docker for pains script

### LINKED ISSUE #98: Attempt to use docker for pains script

### PR DESCRIPTION
**Pull request by sarah-witt**

### CODE REVIEW

**Comment by aislinblack** [comment]
Hi Sarah! Working on running this. I keep getting this error `Error response from daemon: pull access denied for ianwatson/lilly-medchem-rules, repository does not exist or may require 'docker login': denied: requested access to the resource is denied` any idea how to fix it?

**Comment by sarah-witt** [comment]
@aislinblack Whoops yeah there's a typo in the readme it should be: `docker pull ianwatson/lilly_medchem_rules:v1.2`

**Comment by aislinblack** [comment]
Awesome yeah that fixes it. Works great! Just make sure to update the readme

**Comment by aislinblack** [comment]
Updates work well for me!

**Review by aislinblack — APPROVED** [review]
This works well for me! Would like to see if @stanleykywu can also run it on his machine 😆

**Review by stanleykywu — APPROVED** [review]
This works great on my end!

**Pull request merged**
